yamllint for .yaml files (#265)

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -4,9 +4,9 @@ name: CI
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
   schedule:
     - cron: "0 0 * * *"
 
@@ -16,26 +16,29 @@ jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-python@v2
-    - name: Upgrade pip and install linters
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install flake8 pydocstyle packaging
-    - name: flake8 PEP compliance checks
-      run: python -m flake8 anesthetic tests
-    - name: pydocstyle documentation style checks
-      run: python -m pydocstyle --convention=numpy anesthetic
-    - name: Count missing test fixtures
-      run: |
-        if [ $( grep -L 'close_figures_on_teardown' $(grep -l 'matplotlib' tests/test*.py) | wc -w ) -ne 0 ]
-        then
-        missing_tests=$( grep -L 'close_figures_on_teardown' $(grep -l 'matplotlib' tests/test*.py) )
-        echo "$missing_tests are missing the close_figures_on_teardown fixture."
-        exit 1
-        fi
-    - name: Check version number
-      run: python ./bin/check_version.py
+      - uses: actions/checkout@v2
+      - uses: actions/setup-python@v2
+      - name: Upgrade pip and install linters
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install flake8 pydocstyle packaging
+      - name: flake8 PEP compliance checks
+        run: python -m flake8 anesthetic tests
+      - name: pydocstyle documentation style checks
+        run: python -m pydocstyle --convention=numpy anesthetic
+      - name: Count missing test fixtures
+        run: |
+          if [ $( grep -L 'close_figures_on_teardown'
+          $(grep -l 'matplotlib' tests/test*.py) | wc -w ) -ne 0]
+          then
+          missing_tests=$( grep -L 'close_figures_on_teardown'
+          $(grep -l 'matplotlib' tests/test*.py) )
+          echo "$missing_tests are missing the
+          close_figures_on_teardown fixture."
+          exit 1
+          fi
+      - name: Check version number
+        run: python ./bin/check_version.py
 
   pip:
     runs-on: ${{ matrix.os }}
@@ -53,27 +56,27 @@ jobs:
             extras: true
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install -e ".[test]"
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install -e ".[test]"
 
-    - name: Install extra dependencies
-      if: ${{ matrix.extras }} 
-      run: |
-        python -m pip install -e ".[extras]"
+      - name: Install extra dependencies
+        if: ${{ matrix.extras }}
+        run: |
+          python -m pip install -e ".[extras]"
 
-    - name: Test with pytest
-      run: python -m pytest --cov=anesthetic tests
+      - name: Test with pytest
+        run: python -m pytest --cov=anesthetic tests
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1
 
   conda:
     runs-on: ${{ matrix.os }}
@@ -88,22 +91,22 @@ jobs:
             python-version: '3.10'
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: conda-incubator/setup-miniconda@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: conda-incubator/setup-miniconda@v2
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Install dependencies
-      shell: bash -l {0}
-      run: |
-        conda config --append channels conda-forge
-        conda install pytest pytest-cov
-        conda install scipy numpy pandas matplotlib
+      - name: Install dependencies
+        shell: bash -l {0}
+        run: |
+          conda config --append channels conda-forge
+          conda install pytest pytest-cov
+          conda install scipy numpy pandas matplotlib
 
-    - name: Test with pytest
-      shell: bash -l {0}
-      run: python -m pytest --cov=anesthetic tests
+      - name: Test with pytest
+        shell: bash -l {0}
+        run: python -m pytest --cov=anesthetic tests
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1
